name: GPT-3.5 Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Run GPT-3.5 review
      run: python .github/scripts/gpt_review.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
